### ISSUE TITLE
Feature: Home Page

### ISSUE THREAD

**Issue by mateuszdomagala** [mateuszdomagala/vue-rest-countries-api#3]
# Epic Title

Feature: Home Page

## Epic Description

This feature will add a home page where the user can view a list of countries, filter by region and search for a specific country. 

<img src="https://res.cloudinary.com/dz209s6jk/image/upload/v1554827486/Challenges/jfrcfmcisi1xiwm4rl1s.jpg" />

## List of Tasks (Complete in order)

1. [x] [See all countries from the API on the homepage](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/4)
2. [x] [Search for a country using an input field](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/5)
3. [x] [Filter countries by region](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/6)
4. [x] [Click on a country to see more detailed information on a separate page](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/7)
5. [x] [Toggle the color scheme between light and dark mode](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/8)
