### ISSUE TITLE
Feature: Country Page

### ISSUE THREAD

**Issue by mateuszdomagala** [mateuszdomagala/vue-rest-countries-api#9]
# Epic Title

Feature: Country Page

## Epic Description

This feature will add a country page where the user can see all country details and click through to the border countries.

<img src="https://i.imgur.com/UMMjEK8.jpeg" />

## List of Tasks (Complete in order)

1. [x] [Initial Layout of the Country Page](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/10)
2. [x] [Click through to the border countries on the detail page](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/11)
3. [x] [Go back button](https://github.com/mateuszdomagala/vue-rest-countries-api/issues/12)
